influx-url = "http://localhost:8086"
influx-skip-verify = true
influx-auto-create-db = true
#influx-pem-file = "/path/to/cert.pem"
influx-clients = 10

mongo-url = "localhost"
# use the default MongoDB port on localhost
mongo-skip-verify = true
#mongo-pem-file = "/path/to/cert.pem"

replay = false
# process all events from the beginning of the oplog

resume = false
# save the timestamps of processed events for resuming later

resume-name = "mongofluxd"
# the key to store timestamps under in the collection mongoflux.resume

verbose = false
# output some information when points are written

direct-reads = true
# read events directly out of mongodb collections in addition to tailing the oplog

exit-after-direct-reads = true
# exit the process after direct reads have completed. defaults to false to continuously read events from the oplog

[[measurement]]
namespace = "rocketchat.rocketchat_room"
fields = ["_id", "t", "name", "msgs", "default", "_updatedAt", "lm"]
timefield = "ts"
precision = "ms"

[[measurement]]
namespace = "rocketchat.rocketchat_message"
fields = ["_id", "msg", "rid", "bot", "username", "u._id", "u.username", "_updatedAt"]
timefield = "ts"
precision = "ms"

[[measurement]]
namespace = "rocketchat.rocketchat_statistics"
fields = ["_id", "totalUsers", "activeUsers", "nonActiveUsers", "onlineUsers", "awayUsers", "offlineUsers",
          "totalRooms", "totalChannels", "totalPrivateGroups", "totalDirect", "totalLivechat",
          "totalMessages", "totalChannelMessages", "totalDirectMessages", "totalLivechatMessages" ]
timefield = "_updatedAt"
precision = "ms"
